language: generic
os: linux

cache:
  directories:
    - /nix/store

install:
  - bash ./scripts/install-nix.sh
  - git clone https://github.com/eta-lang/eta-nix.git
  - mkdir -p ~/.config/nixpkgs/overlays
  - ln -s ${PWD}/eta-nix/overlay.nix ~/.config/nixpkgs/overlays/eta-overlay.nix

script:
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - export NIXPKGS="https://github.com/NixOS/nixpkgs-channels/archive/nixos-18.09.tar.gz"
  - export NIX_PATH=nixpkgs=${NIXPKGS}
  - "nix-shell -p 'etaPackages.etaWithPackages (p: [])' --run 'eta src/Main.hs'"
