language: generic
os: linux

install:
  - bash ./scripts/install-nix.sh
  - git clone https://github.com/eta-lang/eta-nix.git
  - mkdir -p ~/.config/nixpkgs/overlays
  - ln -s $PWD/eta-nix/overlay.nix ~/.config/nixpkgs/overlays/eta-overlay.nix

script:
  - nix-shell -p 'etaPackages.etaWithPackages (p: [])' --run 'eta src/Main.hs'
