sudo: required
language: generic
os: linux

cache:
  directories:
    - $HOME/nix-cache

install:
  - bash ./scripts/install-nix.sh
  - git clone https://github.com/eta-lang/eta-nix.git
  - mkdir -p ~/.config/nixpkgs/overlays
  - ln -s ${PWD}/eta-nix/overlay.nix ~/.config/nixpkgs/overlays/eta-overlay.nix
  - 'if [ "$(ls -A $HOME/nix-cache)" ]; then sudo rm -rf /nix/* ; cp -a $HOME/nix-cache/* /nix ; fi'

before_cache: 'if [ ! "$(ls -A $HOME/nix-cache)" ]; then cp -a /nix/* $HOME/nix-cache ; fi'

cache:
  directories:
    - $HOME/nix-cache

script:
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - export NIXPKGS="https://github.com/NixOS/nixpkgs-channels/archive/nixos-18.09.tar.gz"
  - export NIX_PATH=nixpkgs=${NIXPKGS}
  - "nix-shell -p haskell.compiler.ghc7103 --command 'ghc --version'"
  - "nix-shell -p etaPackages.eta-repl --command 'echo ok'"
  - "nix-shell -p etaPackages.eta-boot-meta --command 'echo ok'"
  - "echo ok #nix-shell -p 'etaPackages.etaWithPackages (p: [])' --run 'eta src/Main.hs'"
